version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'mick'
    labels:
      - 'dependencies'
      - 'php'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(dev)'
      include: 'scope'
    versioning-strategy: 'auto'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
    open-pull-requests-limit: 15
    reviewers:
      - 'mick'
    labels:
      - 'dependencies'
      - 'javascript'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(dev)'
      include: 'scope'
    groups:
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-*'
      inertia:
        patterns:
          - '@inertiajs/*'
          - '@inertiajs/react'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      radix:
        patterns:
          - '@radix-ui/*'
      lucide:
        patterns:
          - 'lucide-react'

